### ISSUE TITLE
[Wrong link]: Sponsor KwesForms links to vercel.com

### ISSUE THREAD

**Issue by bartdeslagmulder** [ahaywood/compressedfm#91]
### Contact Details

bart.deslagmulder@gmail.com

### What happened?

Hi! I've watched the "Svelte & Third Party Javascript" video and you mentioned that compressedfm website was available on GitHub so I had a look around. Nice website!

I've noticed that the link to KwesForms in the sponsors section is linking to vercel.com. I guess it needs to point to https://kwesforms.com ? But as you're using Sanity this is probably content so I cannot open a PR to fix it. 

![image](https://user-images.githubusercontent.com/62296/191106383-80c87ee4-b10f-459b-b85e-481de1300395.png)

Just wanted to mention it. Have a nice day!
Greetings from Belgium

Bart

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahaywood** [comment]
@bartdeslagmulder Thanks for reporting this bug!

**Comment by ahaywood** [comment]
Fixed within Sanity.
